### ISSUE TITLE
Extension causes the JS/TS language server to crash

### ISSUE THREAD

**Issue by bhekanik** [withastro/language-tools#861] opened 2024-04-25 10:52 UTC
Type: <b>Bug</b>

The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: astro-build.astro-vscode, nrwl.angular-console, svelte.svelte-vscode, tamj0rd2.ts-quickfixes-extension, unifiedjs.vscode-mdx. Please try disabling these extensions before filing an issue against VS Code.

Extension version: 2.8.6
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 23|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|--crash-reporter-id 94d24443-6550-459a-b231-1fb8560994b2 --crash-reporter-id 94d24443-6550-459a-b231-1fb8560994b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
showvideot:31016892
chatpanelc:31018788
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790

```

</details>

**Comment by Princesseuh** [comment] 2024-04-25 17:28
Duplicate of https://github.com/withastro/language-tools/issues/850

**Closed by Princesseuh** 2024-04-25 17:28 UTC
Labels: needs triage
