### ISSUE TITLE
🐛 BUG: Expression expected error if '---' exists in frontmatter regardless of context

### ISSUE THREAD

**Issue by GV79** [withastro/language-tools#457] opened 2022-12-19 01:33 UTC
### Describe the Bug

When adding a valid JS expression/statement within the frontmatter of an `.astro` file that contains `---`, we get an error within the text editor stating `Expression expected`.

![image](https://user-images.githubusercontent.com/24909563/208330562-ab09b5fe-3f25-4263-b360-64881be37d34.png)

Not the most common error but confused me initially when I was formatting `console.log` statements. Seems like some existing logic may need to be updated somewhere to specifically look for the `---` code fence preceded and followed by a newline character?

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Add any type of expression/statement within the frontmatter that contains the Astro code fence (i.e. storing `---` within a variable, logging, comment, regex...etc.) 
3. Extension in VSCode shows TS error `Expression expected.`

**Comment by Princesseuh** [comment] 2022-12-19 01:51
Thank you for reporting this issue!

The TypeScript error part is fixed in the current pre-release. Further work is needed for some other contexts, but it should already make the experience much better.

Additionally, this is a duplicate of https://github.com/withastro/language-tools/issues/248, so I'll be closing this issue in favor of it. Thank you again for reporting this!

**Closed by Princesseuh** 2022-12-19 01:51 UTC
