### ISSUE TITLE
🐛 BUG: vue files cannot be resolved when using together with `vue.volar` extension

### ISSUE THREAD

**Issue by leifmarcus** [withastro/language-tools#451] opened 2022-11-16 21:13 UTC
### Describe the Bug

When working in an astro project that contains vue components and astro components, the typescript module resolution gets problems with either the astro files or the vue files depending on the setup.

1. `vue.volar` extension is used with the [takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) and the `astro-build.astro-vscode` is also activated: `*.astro` files **cannot** be resolved in VS Code, but `*.vue` files **can**.
2. `vue.volar` extension is used without the [takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) and `astro-build.astro-vscode` is also activated: `*.astro` files **can** be resolved, but `*.vue` files **cannot**

### Steps to Reproduce

1. `npm init astro` using template framework-vue
2. create any typescript file, that imports a vue component and an astro component.
3. install `astro-build.astro-vscode` and `vue.volar` extension in VS Code
4. toggle between _takeover mode_ and see the import errors in VS Code
5. Depending on if the _takeover mode_ is active or not you VS Code is not able to resolve either `*.vue` files or `*.astro` files.

**Comment by leifmarcus** [comment] 2022-11-16 21:19
Please also see issue [2126](https://github.com/johnsoncodehk/volar/issues/2126) on the Volar Extension repository

**Comment by johnsoncodehk** [comment] 2022-12-18 20:58
TS Plugin APIs of different extensions will cover each other, I think the TS Plugin-based solution can not support this use case. And as I know there is no other feasible solution currently.

But I think we may able to search a solution on Volar's infrastructure. I would like to know @Princesseuh's stance about this, do you want to use Volar framework to refactor Astro language server? Volar is a framework for creating LSP servers that support multiple languages, I think we can implement [Volar's takeover mode](https://vuejs.org/guide/typescript/overview.html) for Astro language server, and combine language features of two language servers into a single language server under certain conditions through some conventions (But each extension does not need to containing other extension features.) so that supports .astro and .vue in .ts in single language server is possible. Since this is also something that has never been attempted in the past, and requires collaboration across extensions, some challenges can be expected.

Absolutely no push, I have a lot of respect for all the developers who do this and they works, I know that it's quite difficult and heavy work, so therefore absolutely respect the wishes of @Princesseuh.

**Comment by Princesseuh** [comment] 2022-12-22 20:04
> But I think we may able to search a solution on Volar's infrastructure. I would like to know @Princesseuh's stance about this, do you want to use Volar framework to refactor Astro language server?

Hello! Sorry for the late reply, I was on holiday leave. 

This is something I've actually been wondering about ever since seeing your PRs with the experimental Svelte language server on Volar

I discussed this with the team, and we all agree that if it's a major improvement, that we should do it or at least consider it. Personally, I do believe that it could be an improvement, but I'm unsure on the following points:

- Volar moves insanely fast, will it be hard for us to keep up downstream?
- Due to the previous point, I've (totally anecdotal) felt like I've often had stability issues with Volar when working with Vue files. One day everything worked, the next day there was issues etc. Is this something we might suffer from downstream?
- How easy will it be for us to achieve our Vue, Svelte, JSX resolutions in Astro files using Volar? I have not tried Volar's API regarding adding support for other file extensions, but I seem to remember it being a bit tied to adding one file format at a time (could be 100% wrong on this, for sure)
- Our `astro check` command currently uses our language server to run, including both `tsc`-like diagnostics and diagnostics from our compiler. Will it be possible to achieve this with Volar?

I also have some worries about "losing control over the language server" since I do know Volar's codebase as well. But I think this point I'd be able to get over after spending some time in Volar's code.

I'd love to first try to make a prototype of this to see if there's tangible benefits, but ultimately: I am interested. Volar is awesome work :)

**Comment by johnsoncodehk** [comment] 2022-12-23 02:04
> Volar moves insanely fast, will it be hard for us to keep up downstream?

If you guys decide to adopt it, I will at least be involved in maintaining the part that interacts with Volar. For me it's just adding withastro/language-tools to multiworkspace, so I can do it for very little cost.

> Due to the previous point, I've (totally anecdotal) felt like I've often had stability issues with Volar when working with Vue files. One day everything worked, the next day there was issues etc. Is this something we might suffer from downstream?

Sorry about that... I hope things improve for you after 1.0. In fact, most of the regressions come from the Vue part (vue-langauge-tools/* in the repo), and the core modules (packages/*) that affect you are relatively stable. On the other hand, you can also lock the version of the core module and decide its update strategy yourself.

Specifically, you may need to regularly review the core module update PR submitted by me, and only merge it when you think there is no problem. (You can check if Volar repo don't have new issue in a few days for new version)

> How easy will it be for us to achieve our Vue, Svelte, JSX resolutions in Astro files using Volar? I have not tried Volar's API regarding adding support for other file extensions, but I seem to remember it being a bit tied to adding one file format at a time (could be 100% wrong on this, for sure)

The virtual files for Astro, Vue, Svelte (or even JSX if you want) are provided by you, so you have complete freedom. On the other hand, since the Volar repo has implemented Vue, Svelte, Angular's virtual files support, you can reuse it in the Astro language server if you want.

Another step will be the merging of multiple language servers I mentioned. The Astro language server may not need to process .vue, but will automatically recognize the .vue file type when the user installs Vue Language Features in VSCode.

For multiple file formats support, you can check the Angular example which has supports .html and .ts.

https://github.com/johnsoncodehk/volar/blob/8e5cec4a30fdc53e52b28d0fe52befc19e32d634/examples/angular-language-server/src/index.ts#L9-L14

> Our astro check command currently uses our language server to run, including both tsc-like diagnostics and diagnostics from our compiler. Will it be possible to achieve this with Volar?

For Vue we use vue-tsc + Hook API to support this kind of use case, I am not sure if that is suitable for you, I can also see how `astro check` supports Volar.

> I also have some worries about "losing control over the language server" since I do know Volar's codebase as well. But I think this point I'd be able to get over after spending some time in Volar's code.

You don't lose control, Volar is pretty open to changing the code if there's something it can't do, I can add you to the maintainers if you willing.

> I'd love to first try to make a prototype of this to see if there's tangible benefits, but ultimately: I am interested. Volar is awesome work :)

Can I make it for you? Will take hours and I'd be happy to do it, but I'm not sure if you want to try it yourself. And thank you!

**Comment by leifmarcus** [comment] 2022-12-28 15:49
@Princesseuh and @johnsoncodehk thanks for looking into it. Really appreciate it!

**Comment by johnsoncodehk** [comment] 2023-01-04 01:10
@Princesseuh Here is a template for you :)
 https://github.com/volarjs/language-tools-starter

**Comment by Princesseuh** [comment] 2023-01-04 01:16
> @Princesseuh Here is a template for you :)
>  https://github.com/volarjs/language-tools-starter

Sorry for the late answer, we got back into our holiday period after my previous message 😅

This template looks amazing! I don't have much bandwidth at the moment (we're currently heading into Astro 2.0) to try this out, but I'd love to experiment with it and see concretely if/how it'd improve the current experience

This template will definitely make it easier. I'll try to find some time!

**Comment by johnsoncodehk** [comment] 2023-06-29 06:11
This problem should be resolved in TypeScript Vue Plugin 1.8.1 without use takeover mode.

**Comment by leifmarcus** [comment] 2023-06-29 12:17
@johnsoncodehk and @Princesseuh, I actually found a solution to the problem, that astro files and vue files cannot be imported at the same time.

When I define my `env.d.ts` as follows, then it works with both extensions active

```ts
declare module '*.vue' {
  import type { DefineComponent } from 'vue';
  const component: DefineComponent<{}, {}, any>;
  export default component;
}

declare module '*.astro' {
  import type { AstroComponentFactory } from 'astro/internal';
  const component: AstroComponentFactory;
  export default component;
}
```

**Comment by Princesseuh** [comment] 2023-06-29 13:29
While it does fix the error showing, all other features (cross file renaming, file references etc) won't work with this, so we still need to have a proper fix ourselves

**Comment by leifmarcus** [comment] 2023-07-05 18:07
@Princesseuh, you are right. At least it is possible to work with both extensions activated.

**Comment by Princesseuh** [comment] 2023-07-17 17:49
Our part of this is now released and things should now work when takeover mode is disabled, for full support with takeover mode, a lot of work will have to be done that's mostly unrelated to Astro apart from keeping our TypeScript plugin updated, as such I'll be closing this issue, thank you everyone!

**Closed by Princesseuh** 2023-07-17 17:49 UTC
Labels: ts-plugin, vue
