### ISSUE TITLE
🐛 BUG: False positive error message

### ISSUE THREAD

**Issue by jetjtx** [withastro/language-tools#625] opened 2023-08-12 14:19 UTC
### Describe the Bug

With twice `onclick="samecall()"` in the HTML markup, Astro extension in VSCode produces false positive error message: `';' is expected`;

When I removed either one, the error message wll disappear.

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. ...
3. ...
4. ...
5. Error! Describe what went wrong (and what was expected instead)...

**Comment by Princesseuh** [comment] 2023-08-12 15:45
Duplicate of https://github.com/withastro/language-tools/issues/587

**Closed by Princesseuh** 2023-08-12 15:45 UTC
