### ISSUE TITLE
🐛 BUG: VSCode code highlighting after script attributes

### ISSUE THREAD

**Issue by igl** [withastro/language-tools#551] opened 2023-06-01 13:19 UTC
### Describe the Bug

Using atteributes with values wrapped in single-quotes (`'`) that contain script-content currently break the highlighting for the rest of the file.

This does not happen when using double-quotes `"`.

Here is a example:
<img width="936" alt="astro-highlight" src="https://github.com/withastro/language-tools/assets/293519/2bdbca41-aa32-4c32-842e-53349910c1dc">

1) Broken
2) OK: No `onload=''` attribute
3) OK: Double-Quote on `onload=''` attribute

i used the latest version of the VSCode plugin, i also tried the pre-release version without success.

### Steps to Reproduce

1. Add a script tag with `onload` attribute to any .astro file

**Comment by Princesseuh** [comment] 2023-06-01 16:52
Closing as a duplicate of https://github.com/withastro/language-tools/issues/530

**Closed by Princesseuh** 2023-06-01 16:52 UTC
