### ISSUE TITLE
Error "Module '"*.astro"' has no default export." when importing components with conditional rendering

### ISSUE THREAD

**Issue by krolebord** [withastro/language-tools#386] opened 2022-08-26 08:43 UTC
### What version of `astro` are you using?

1.0.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac, Linux

### Describe the Bug

Importing astro component with conditional rendering in it (`{condition && <p>text</p>}`) causes `Error "Module '*.astro"' has no default export."`

The error seems not to affect `astro build` or `astro dev` but is shown in the editor and in the output of `npx astro check`

### Link to Minimal Reproducible Example

https://stackblitz.com/withastro-astro-piqjnh

### Participation

- [X] I am willing to submit a pull request for this issue

**Comment by Princesseuh** [comment] 2022-08-26 12:40
Hello! Thank you for creating this issue. This is an issue with our current way of parsing Astro files inside the language server. We're currently in the process to migrating to a new parser. Progress can be tracked here https://github.com/withastro/language-tools/pull/335

In the meantime, I'll close this issue as a duplicate of https://github.com/withastro/language-tools/issues/378. Thank you again for creating this issue!

**Closed by Princesseuh** 2022-08-26 12:40 UTC
