### ISSUE TITLE
🐛 BUG: Template string prop styntax not supported

### ISSUE THREAD

**Issue by zadeviggers** [withastro/language-tools#363] opened 2022-08-05 23:42 UTC
### Describe the Bug

The attribute template string shorthand syntax shows an error in VSCode (and in GitHub, interestingly), but it builds just fine.

```astro
---
const fruits = ["Apple", "Banana", "Pear"];
---

<ul>
    {fruits.map(fruit => <li title=`The best fruit is ${fruit}`>{fruit}</li>)}
</ul>
```

<img width="598" alt="Screen Shot 2022-08-06 at 11 33 20 AM" src="https://user-images.githubusercontent.com/74938858/183223595-35e01b3a-0e38-4af6-a56f-14f79aaec0b0.png">
<img width="243" alt="Screen Shot 2022-08-06 at 11 34 51 AM" src="https://user-images.githubusercontent.com/74938858/183223636-fd85b330-c67d-4de8-aea8-9e5144a89710.png">

### Steps to Reproduce

1. `npm init astro` using template basics
2. Use the backtick attribute shorthand (``<div title=`My ${Math.random() > 0.5 ? "awesome" : "cool"} title`>Hover me!</div>``) on an element
3. Error! It should behave just like a normal prop

### Other notes
Posibly related to #225

**Comment by Princesseuh** [comment] 2022-08-06 00:11
Thank you for filling this issue, it'll be fixed when we migrate to the compiler TSX output in https://github.com/withastro/language-tools/pull/335

For now, I'll close this as a duplicate of https://github.com/withastro/language-tools/issues/357

**Closed** 2022-08-06 00:11 UTC
Labels: bug, needs-compiler
