### ISSUE TITLE
🐛 BUG: Components outside of project dir not found

### ISSUE THREAD

**Issue by lifeisfakenews** [withastro/language-tools#611] opened 2023-07-23 11:47 UTC
### Describe the Bug

The extension shows `.astro` files that are outside the project folder as not found, even though I can Ctrl click to them and the project builds fine using them.

Because I have 2 projects which are part of the same website, i have a folder `resources/compontents` containing components like modals and dropdowns which i use on both sites. This helps to keep the design consistent between parts of the site and makes it easier to update, however VSC marks the imports with a red underline saying `Cannot find module '../../../resources/components/Dropdown.astro' or its corresponding type declarations.ts(2307)`. This only happens for components outside the project folder. Both projects build fine using the components.
![image](https://github.com/withastro/language-tools/assets/86294896/b1727459-2017-4a92-89c5-f9647fa17e25)
![image](https://github.com/withastro/language-tools/assets/86294896/40b11092-2380-4bc8-a3f7-bea021c97593)

### Steps to Reproduce

1. `npm init astro` using template i cant remember prolly the default one tho it doesn't matter
2. create a folder at same level at the project folder (e.g. `/folder/astro-project`, `/folder/resources`)
3. put a component inside the folder
4. import and use the component on a page inside your project
5. notice that VSC underlines the import
6. project should build fine

**Comment by johnsoncodehk** [comment] 2023-07-24 03:26
Duplicate of #609

**Closed** 2023-07-24 07:08 UTC
