### ISSUE TITLE
🐛 BUG: Using a property as a dynamic tag marks TS props as unused

### ISSUE THREAD

**Issue by crutchcorn** [withastro/language-tools#972] opened 2024-10-19 14:54 UTC
### Describe the Bug

When using code like this:

```astro
---
interface Props {
  as: string;
}

const { as } = Astro.props;
const As = as;
---

<As>
  <slot />
</As>
```

And running `pnpm astro check` it shows an error:

```
error ts(6196): 'Props' is declared but never used.
```

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Use the code above in a component
3. Run `pnpm astro check`
4. Error! `error ts(6196): 'Props' is declared but never used.`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-check-errors?file=src%2Fcomponents%2FCard.astro&on=stackblitz

**Comment by Princesseuh** [comment] 2024-11-04 21:52
Duplicate of https://github.com/withastro/compiler/issues/927

**Closed by Princesseuh** 2024-11-04 21:52 UTC
Labels: needs triage
