### ISSUE TITLE
🐛 BUG: File move and renames are not properly tracked 

### ISSUE THREAD

**Issue by Princesseuh** [withastro/language-tools#297] opened 2022-05-22 18:04 UTC
### Describe the Bug

Moving a file or renaming one (which is effectively on a technical level the same thing) does not properly update the module resolution cache and snapshots, which leads to many undesirable behavior such as providing completions for components that doesn't exist, some errors being wrong (ex: a file doesn't exist anymore but TS does not error on them)

When a file is moved / renamed, we should catch that event and properly update our caches

### Steps to Reproduce

1. Import a component in an Astro file
2. Rename said component
3. No errors inside original file even though the file does not exist anymore!

**Comment by Gers2017** [comment] 2022-09-03 03:21
Hey @Princesseuh I'm not sure if this is related but I have a similar issue.

When I try to rename an interface a duplicate of the new name appears at the bottom of the file.

I have the Astro vscode extension installed but I'm not sure if this is caused by vscode or by the Astro extension

![astro-rename-bug](https://user-images.githubusercontent.com/49139988/188253791-20d70286-09a1-4b9d-9e93-3866ff2b51cd.gif)

**Comment by Princesseuh** [comment] 2022-09-03 03:41
> Hey @Princesseuh I'm not sure if this is related but I have a similar issue.
> 
> When I try to rename an interface a duplicate of the new name appears at the bottom of the file.
> 
> I have the Astro vscode extension installed but I'm not sure if this is caused by vscode or by the Astro extension
> 
> ![astro-rename-bug](https://user-images.githubusercontent.com/49139988/188253791-20d70286-09a1-4b9d-9e93-3866ff2b51cd.gif)
> 

Hello! 

That problem is more so related to this https://github.com/withastro/language-tools/issues/368. This issue is strictly about renaming  / moving files in the explorer 😄

**Closed** 2022-09-26 19:37 UTC
Labels: bug, p5-urgent
