### ISSUE TITLE
🐛 BUG: When VsCode setting "organizeImports" is enabled, saving will result in "crashing"

### ISSUE THREAD

**Issue by lauhon** [withastro/language-tools#443] opened 2022-11-04 09:24 UTC
### Describe the Bug

In VsCode's `settings.json` its possible to automatically organize imports with this setting:

```
 "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
```

If this is enabled and the astro language support is enabled, saving will make vscode freeze in .astro files.
I think the bug only occurs when the order of import is actually changed automatically.

As soon as I add the following to my `settings.json` I can save the file without a problem:

```
 "[astro]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": false
    }
  }
```

Note: I am working on an M1 Mac

### Steps to Reproduce

1. Install VSCode
2. Install Astro Language Support
3. Set `organizeImports`to true
4. Create an .astro file that imports multiple components in an "incorrect" order
5. Try to save the file

**Comment by Princesseuh** [comment] 2022-11-04 17:28
Hmm, I am not able to reproduce. On my computer, imports automatically get reorganized on save as expected.

Do you have more information? Does this happens on specific files, specific amount of imports etc?

**Comment by lauhon** [comment] 2022-11-04 19:05
Interesting,  I mean maybe its a problem on my machine for some reason?

I suspected that it has to do with my project, which is a quite large monorepo. But I could also reproduce the Problem on this example project: https://github.com/mhyfritz/astro-landing-page

this is my complete settings.json

```
{
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "Electron",
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.formatOnSave": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
  "diffEditor.ignoreTrimWhitespace": false,
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "cSpell.userWords": ["Fastify"],
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "typescript.updateImportsOnFileMove.enabled": "always",
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "files.associations": {
    "*.astro": "astro"
  },
  "[astro]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  }
}
```

I have a bunch of other extensions installed, but I think most of them should not be relevant. Here are the ones that seem relevant to me:

- Prettier
- Path Intellisense
- IntelliCode
- EsLint
- Electron Color Theme

**Comment by lauhon** [comment] 2022-11-04 19:07
Also I want to point out that without the `organizeImports` setting I have no problems, so even for me this is not very important. I dont want to waste your time, if you feel like it I understand if you just close the Issue :D

**Comment by cyrdam** [comment] 2022-11-04 21:55
Hi, same issue for me, I also tried a test with this:

```json
{
	"astro.typescript.codeActions.enabled": false
}
```

And it also had the same result for not getting into a save-format loop. I also suspect the issue within the `organizeImports` setting.

**Comment by Princesseuh** [comment] 2022-11-05 04:29
Marking as a bug, but I still cannot reproduce 😕

Is there any output in the Output panel for the Astro extension when this happens?

**Comment by keupoz** [comment] 2022-11-05 11:25
Having same issue. Nothing in output tab

**Comment by keupoz** [comment] 2022-11-05 11:50
Seems like it's not only Astro related
microsoft/vscode#165326

**Comment by aamirbinabd** [comment] 2022-11-06 18:28
I reported something similar here: #444

**Comment by Princesseuh** [comment] 2022-11-11 15:40
VS Code 1.73.1 was released with a fix for this. Thank you to everyone who reported this issue!

**Closed by Princesseuh** 2022-11-11 15:40 UTC
Labels: bug, upstream
