### ISSUE TITLE
🐛 BUG: typing error in astro components after updating to version 2.6.0 vscode extension

### ISSUE THREAD

**Issue by maqueise** [withastro/language-tools#751] opened 2024-01-08 22:45 UTC
### Describe the Bug

After updating to the latest version, typing errors are occurring:

Error in astro component

https://github.com/withastro/language-tools/assets/6271023/07cb48fb-e216-4df0-98c5-82576ca224c4

> Type '{ children: Element[]; class: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.>   Property 'class' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'. Did you mean 'className'?ts(2322)

> Type '{ children: Element; title: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Props'.ts(2322)

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. ...
3. ...
4. ...
5. Error! Describe what went wrong (and what was expected instead)...

**Comment by Princesseuh** [comment] 2024-01-09 00:17
Could you share a reproduction?

**Comment by nickgraffis** [comment] 2024-01-09 00:34
@maqueise FYI I had the same issue. 

I tried to make a reproduction, or to trace back what package caused the issue. I was not able to unfortunately. 

But, a clean install did fix the issue. 

Hope it helps

**Comment by yoyo837** [comment] 2024-01-09 00:52
Same here.

**Comment by Princesseuh** [comment] 2024-01-09 01:35
Without a repro I unfortunately cannot do much 😅 Is there any chances all of you are on versions of Astro older than 4.0.6?

**Comment by Princesseuh** [comment] 2024-01-09 01:53
Fixed in 2.6.1. Sorry for the inconvenience!

**Comment by gluax** [comment] 2024-01-09 02:37
This is not fixed for me in `2.6.1`

**Comment by yoyo837** [comment] 2024-01-09 02:51
> This is not fixed for me in `2.6.1` Downgrading to `2.5.6` does fix the issue though.

Me too. I‘m use Astro@3.x, I'll try to make a reproduction link.

**Comment by Princesseuh** [comment] 2024-01-09 02:59
Hmm, that's very weird. I cannot reproduce the issue anymore on 2.6.1, but I'll admit I didn't try every Astro version, just `4.0.0`.

**Comment by yoyo837** [comment] 2024-01-09 03:06
> > This is not fixed for me in `2.6.1` Downgrading to `2.5.6` does fix the issue though.
> 
> Me too. I‘m use [Astro@3.x](mailto:Astro@3.x), I'll try to make a reproduction link.

Sadly, Can not reproduce this issue with a newly created mini project, so I will try to delete some files from my own project to provide a minimal reproduction.

**Comment by Princesseuh** [comment] 2024-01-09 03:08
I found the issue, I couldn't reproduce it because it only happens in the deployed version and not the dev version I was using. Will release another patch shortly, sorry for the inconvenience!

**Comment by yoyo837** [comment] 2024-01-09 04:10
Thanks for your work, it looks like I don't need to prepare a minimal reproduction anymore.

**Comment by Princesseuh** [comment] 2024-01-09 06:34
Just released 2.6.2 that seems to work for me locally, let me know how that works!

**Comment by yoyo837** [comment] 2024-01-09 06:55
Its works pretty for me. Thanks again.

**Comment by maqueise** [comment] 2024-01-09 13:56
Issue resolved, errors do not occur in v2.6.2, thank you.

**Closed** 2024-01-09 13:59 UTC
Labels: - P5: urgent
