### ISSUE TITLE
🐛 BUG: Comments are HTML Style in VSCode (by default)

### ISSUE THREAD

**Issue by gvkhna** [withastro/language-tools#619] opened 2023-07-29 23:11 UTC
### Describe the Bug

https://github.com/withastro/language-tools/blob/93ae6e5fdbd45169a42eddf6736a7c8cb8df23b9/packages/vscode/languages/astro-language-configuration.json#L3

Based on this configuration. The standard block comment with VSCode is `<!-- -->`. I'm reporting this as a bug for several reasons. 

1. html comments are visible in output
2. Multiline comments break when there are already html comments inside of it
3. There's no functional way to remove html comments in astro output

Typical comments aren't supposed to be produced/preserved in output. Stemming from behavior of compilers ignoring them. Please change to javascript style comments which seem to be working great! {/* */} solves multiline and encapsulation issues as well as not being preserved in output.

Workaround: I currently am using the `"arturodent.custom-language-syntax"` extension to switch this behavior in vscode.

With the following in my `.vscode/settings.json` in the project.
```json
{  
"custom-language-properties": {
    "astro.comments.blockComment": ["{/*", "*/}"]
  }
}
```

As a workaround it is acceptable.

**Comment by Princesseuh** [comment] 2023-07-30 07:09
Unfortunately, since this is only a preference thing, it's not really a bug. Someone will prefer HTML comments for the total opposite reasons. (And historically, that's what people preferred, hence why it's set up that way)

I wish we could make this more dynamic, allowing users to configure it and stuff.

**Comment by Princesseuh** [comment] 2023-09-14 11:23
Closing since this is not a bug and there's no perfect solution. I suggest making a discussion on the roadmap repo: https://github.com/withastro/roadmap/discussions

**Closed by Princesseuh** 2023-09-14 11:23 UTC

**Comment by cdtut** [comment] 2023-11-19 00:53
@Princesseuh Astro doesn't have option to remove html comments from output so I agree that this is a bug because sensitive information can show in public output accidentally. This has already happened.

Can it be a toggle feature in settings which style to use? It's difficult development experience to change html comments to astro comments manually and not always possible to remember.

Astro has great comment syntax, why would official astro extension not make it available to use?

**Comment by Princesseuh** [comment] 2023-11-19 01:27
> @Princesseuh Astro doesn't have option to remove html comments from output so I agree that this is a bug because sensitive information can show in public output accidentally. This has already happened.
> 
> Can it be a toggle feature in settings which style to use? It's difficult development experience to change html comments to astro comments manually and not always possible to remember.
> 
> Astro has great comment syntax, why would official astro extension not make it available to use?

It cannot be made configurable, unfortunately. VS Code doesn't support that.

As my answer previously says, it's entirely subjective which one people want, both are valid. It's fairly likely for someone to not mind it using HTML comments that are shown in the output, because they could very well be used to that behavior from HTML.

**Comment by JaneSmith** [comment] 2024-09-17 10:05
I also think this behaviour should be changed. I expect "real" comments by default (i.e. ones that won't end up in final output), not HTML-style ones.

I tried the workaround posted in the OP, but unfortunately it doesn't work for me. I installed the extension and added the configuration for it, but I still get HTML comments...
