### ISSUE TITLE
🐛 BUG: Conflicting ImportMeta declarations

### ISSUE THREAD

**Issue by FredKSchott** [withastro/language-tools#65] opened 2021-09-15 05:42 UTC
### Describe the Bug

[This definition](https://github.com/snowpackjs/astro-language-tools/blob/1958d51cd3a4c28c07e77aec3ba646d2bb9556f8/packages/language-server/astro.d.ts#L3-L11) can conflict with my own environment's `import.meta` definitions. For example:

- If I'm using Snowpack with `@types/snowpack-env`
- If I'm using Vite and connected my tsconfig to `vite/types`

An example error that I'm seeing:

```
All declarations of 'hot' must have identical modifiers.js(2687)
Subsequent property declarations must have the same type.  Property 'hot' must be of type '{ readonly data: any; accept(): void; accept(cb: (mod: any) => void): void; accept(dep: string, cb: (mod: any) => void): void; accept(deps: readonly string[], cb: (mods: any[]) => void): void; acceptDeps(): never; dispose(cb: (data: any) => void): void; decline(): void; invalidate(): void; on: { ...; }; }', but h
```

I think it's safe to assume that your environment provides these, and its not the responsibility of the Astro compiler.

### Steps to Reproduce

Do either of the steps above (for Snowpack or Vite) and then see this error in every compiled Astro file (ex: src/pages/index.astro).

**Comment by matthewp** [comment] 2021-09-15 12:33
Hm, the issue is that `astro` doesn't come with either of those things, so using `import.meta.env` produces errors in most Astro projects. The only solution I can think of as the moment is to suppress the errors instead.

Or, I suppose, to do the thing we talked about and require a `tsconfig.json` for TypeScript projects. Let me know what you think.

**Comment by FredKSchott** [comment] 2021-09-15 17:27
Hmm, yea that's a tricky one. Are you able to provide `compilerOptions.types` to the TS compiler when we run it in VSCode? In that case, you could just send `types: ["vite/types"]` to the compiler and get the proper types, without having to maintain them inline. 

If that doesn't work, you might be be able to get away with something like:

```
import type * as vite from 'vite/client';

declare global {
  type ImportMeta = vite.ImportMeta;
}
```

**Comment by matthewp** [comment] 2021-09-15 19:41
So is this an issue for the future? `astro` doesn't come with `vite` either.

**Comment by FredKSchott** [comment] 2021-09-15 20:26
I was using vite because it’s explicit, snowpack just says to install “@types/snowpack-env”. If we make @types/snowpack-env a dependency of Astro, does this problem go away / no inline ImportMeta interface needed?

**Comment by matthewp** [comment] 2021-09-15 22:13
Good question that I'll have to test, as I'm not sure if typescript crawls inside node_modules or not. If so that would be a nice fix.

**Comment by FredKSchott** [comment] 2021-09-16 02:48
It does for @types packages. You can check out how the snowpack TS example projects use @types/snowpack-env (or maybe it’s a dependency of snowpack itself? Can’t remember exactly which)

**Comment by jasikpark** [comment] 2021-09-19 16:51
> It does for @types packages. You can check out how the snowpack TS example projects use @types/snowpack-env (or maybe it’s a dependency of snowpack itself? Can’t remember exactly which)

Typescript looks for type declarations in the package first, and then checks if there's a @types package for it installed

**Comment by Princesseuh** [comment] 2021-12-27 11:18
Now that Astro uses Vite, a lot of users will eventually run into this issue if they're using `import.meta.env` with `types: ["vite/client"]`

I'm not sure if the previous comments are still accurate and available solutions, but I personally think that it would be reasonable to require / strongly encourage using a `tsconfig.json` when using Typescript för proper typing when using import.meta

**Comment by jonathantneal** [comment] 2022-01-19 22:35
Fixed in https://github.com/withastro/language-tools/pull/151 and https://github.com/withastro/language-tools/pull/145 🎉

**Closed by jonathantneal** 2022-01-19 22:35 UTC
