### ISSUE TITLE
🐛 BUG: Variables used in `return` in `.astro` files are ignored by TypeScript. `'<variable>' is declared but its value is never read. ts(6133)`

### ISSUE THREAD

**Issue by drevantonder** [withastro/language-tools#494] opened 2023-03-13 10:36 UTC
### Describe the Bug

Astro's Typescript appears to be ignoring variables in the return value e.g. `return redirect()` in `.astro` files.

When using `astro/tsconfigs/strictest` the variables used in the return value the variables are highlighted with `ts(6133)`: `'<variable>' is declared but its value is never read.`

---

I came across this issue whilst using a helper for my auth in `.astro` files, like so:

```ts
import { requiresSession } from "@/server/auth";

const { session, redirect } = await requiresSession(Astro);
if (!session) return redirect();
```

Where `redirect` is a function that returns `Astro.redirect()`

### Steps to Reproduce

See my [reproduction repo](https://github.com/drevantonder/astro_language-tools_issue-repro) or follow below instructions.

1. `npm create astro@latest`
    1. Empty
    2. Typscript @ **Strictest** _(Strict and base don't highlight, but still complain)_
2. Install dependencies `npm i`
3. Open `pages/index.astro` and add _(I'm using `Math.random` to get around other TS errors)_
```diff
---
+const redirect = () => Astro.redirect('/')
+if (Math.random() > 0) return redirect()
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>Astro</title>
	</head>
	<body>
		<h1>Astro</h1>
	</body>
</html>
```
4. TypeScript will highlight `redirect` with `'redirect' is declared but its value is never read.`

**Comment by Princesseuh** [comment] 2023-03-13 22:06
Closing as a duplicate of https://github.com/withastro/language-tools/issues/476
 
(It's the same underlying issue)

**Closed** 2023-03-13 22:06 UTC

**Comment by drevantonder** [comment] 2023-03-13 22:14
Thanks! Yes, that'd be the same. 👍
