### ISSUE TITLE
🐛 BUG: Widespread Intellisense Issues in Astro Projects in VS Code 1.91.0

### ISSUE THREAD

**Issue by pjosxyz** [withastro/language-tools#892] opened 2024-07-07 09:16 UTC
### What version of @astrojs/language-server are you using?
2.10.0

### What package manager are you using
Bun - Repo: [astro-min-bun](https://github.com/pjosxyz/astro-min-bun)
Npm - Repo: [astro-min-npm](https://github.com/pjosxyz/astro-min-npm)
Bun: 1.1.13 / NPM: 10.7.0 / Node 20.15.0 (all WSL)

### What operating system are you using
Windows10 + WSL2 (2.2.4.0) (Ubuntu 20.04.6 LTS)
(Same issues in Windows10 with Bun and NPM)

### VSCode Version
1.91.0

### Describe the bug
Intellisense in Astro projects is inconsistent and often doesn't work in various scenarios. The behavior seems to vary between different package managers and even within the same project.

### Issues observed

**Interpolating values in HTML**
Intellisense not working

https://github.com/withastro/language-tools/assets/122515043/ad963826-0b9d-419f-a301-6f559a7c7f16

**Auto imports**
Not auto-completing/importing

https://github.com/withastro/language-tools/assets/122515043/3e5a5782-7889-4976-b32d-e4ca13a99590

**Auto finish imports in frontmatter**
Inconsistent behaviour

https://github.com/withastro/language-tools/assets/122515043/854ef1c0-4e32-4455-bf4c-b8e5d710038e

Seems to be quite variable in what wants to work and what doesn't, for instance:

**Inconsistent behavior between Bun and NPM**
- In Bun: Doesn't recognize Astro components but provides correct methods
https://github.com/withastro/language-tools/assets/122515043/c4c84166-8729-445e-aa08-420dc42b594e

- In NPM: Recognizes Astro components but doesn't provide methods

https://github.com/withastro/language-tools/assets/122515043/2c00799d-4271-4552-949c-86584a7896e2

You can see in the video above that "prop1" doesn't get intellisense for string methods. It does in the Bun repo, but fwiw last night in a project I had started with Bun I wasn't getting intellisense so the issue seems to happen ... randomly, or feels like it does at least!

**Intellisense for props**
Untyped: No intellisense

https://github.com/withastro/language-tools/assets/122515043/e181a757-c3da-496c-a79e-8fa44da0dfd4

Typed: Inconsistent intellisense

https://github.com/withastro/language-tools/assets/122515043/31fe5ea5-2a1d-4d28-bfc3-e6b9ebc0e6fd

### Steps to Reproduce

1. Create a new Astro project: npm create astro@latest or bun create astro@latest using the 'Empty' template
2. Create some components and try to use variables
3. Attempt to import components
4. Observe inconsistent or non-functional intellisense

### Additional Notes
The issue seems to occur randomly, making it difficult to pinpoint the exact conditions

For comparison, intellisense works correctly in Next.js projects with the same VSCode/Node/Bun/WSL setup

https://github.com/withastro/language-tools/assets/122515043/547ea839-ec76-4c6f-a7e9-0972c6538236

https://github.com/withastro/language-tools/assets/122515043/082da220-e402-4af2-827e-6a6d8fa94c75

Long time lurker, first time Issue creator... If there's details I've missed or rules I've broken let me know 😃. Thanks!

**Comment by Princesseuh** [comment] 2024-07-07 10:00
There's seems to be a VS Code regression affecting many users in the latest version of VS Code, not too sure what's going on.

**Comment by pjosxyz** [comment] 2024-07-07 10:35
Downgrading VSCode to 1.90.2 seems to have fixed the issue, thanks

**Comment by Princesseuh** [comment] 2024-07-07 10:46
Let's keep it open for other people to see

**Comment by hkbertoson** [comment] 2024-07-07 22:08
Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:54:35.075Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

This is my VSCode Version and it doesnt seem to be working for me. 

![CleanShot 2024-07-07 at 17 08 23](https://github.com/withastro/language-tools/assets/44106297/160aadf2-6717-443e-aaac-7a1fbdb81f03)

**Comment by gavagavas** [comment] 2024-07-08 04:52
@pjosxyz 
Nice to meet you. 
Don't you need to downgrade to 1.89 for it to work properly?

**Comment by Princesseuh** [comment] 2024-07-08 08:48
> Version: 1.90.2 Commit: 5437499feb04f7a586f677b155b039bc2b3669eb Date: 2024-06-18T22:54:35.075Z Electron: 29.4.0 ElectronBuildId: 9728852 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Darwin arm64 23.5.0
> 
> This is my VSCode Version and it doesnt seem to be working for me.
> 
> ![CleanShot 2024-07-07 at 17 08 23](https://private-user-images.githubusercontent.com/44106297/346371554-160aadf2-6717-443e-aaac-7a1fbdb81f03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjg3NjksIm5iZiI6MTcyMDQyODQ2OSwicGF0aCI6Ii80NDEwNjI5Ny8zNDYzNzE1NTQtMTYwYWFkZjItNjcxNy00NDNlLWFhYWMtN2ExZmJkYjgxZjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4NDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxN2RhOTY4N2VlZGUyM2QwNTI5MTMxMDcyMzM5ZDFkNzg1OGUzYjRkMGNlZWUyMGQxYzliMmZlMWZjMTBhMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MgR3D5ozO-tf95Dh8-jIcbtKlkq-dtYz-jB-oEFNo9A)

Does this happen for every component? For `Image` it's unfortunately normal, because a global `Image` exists, so TypeScript doesn't consider that you might be missing an import.

**Comment by Princesseuh** [comment] 2024-07-08 10:05
https://github.com/withastro/language-tools/pull/879 seems to fix the issue for me locally.

**Comment by Princesseuh** [comment] 2024-07-08 12:15
I confirm that this is now fixed in the latest version of the extension. Apologies for the inconvenience.

I will note that this issue was purely dedicated to the regression in VS Code's latest version - I'm sure there's still issues with auto import that exists. Most of which are related to https://github.com/withastro/compiler/issues/862, or https://github.com/withastro/language-tools/issues/800 or other existing issues. 

I will be closing this issue as *this* precise issue is fixed - but understand that other issues related to auto-imports are also being looked at.

**Closed by Princesseuh** 2024-07-08 12:15 UTC
Labels: ecosystem: upstream, - P5: urgent
