### ISSUE TITLE
🐛 BUG: Import auto-completion issue in VS Code for new components

### ISSUE THREAD

**Issue by riki137** [withastro/language-tools#808] opened 2024-02-24 11:22 UTC
### Describe the Bug

When creating a new .astro file (component) in Visual Studio Code, the Astro.js plugin does not automatically provide import auto-completion for the newly created component. This results in manual import statements being required for the new component to be recognized in the code.

### Expected Behavior:
Auto-completion for the import statement should be triggered by the Astro.js plugin when a new component is created, eliminating the need for manual import statements.

### Workaround:
Restarting Visual Studio Code resolves the issue, and auto-completion works as expected for the newly created component.

### Environment:
- Visual Studio Code Version: 1.86.1
- Astro.js Plugin Version: 2.7.5
- Operating System: Linux, Pop!_OS 22.04

### Steps to Reproduce

1. Create a new .astro file (component) in your Astro.js project.
2. Attempt to use the new component in another file.
3. Notice that auto-completion for the import statement is not provided by the Astro.js plugin.

**Comment by Princesseuh** [comment] 2024-02-24 11:46
Duplicate of https://github.com/withastro/language-tools/issues/685

**Closed by Princesseuh** 2024-02-24 11:46 UTC
Labels: needs triage
