### ISSUE TITLE
🐛 BUG: Fails to parse set:html template literal usage

### ISSUE THREAD

**Issue by crutchcorn** [withastro/language-tools#333] opened 2022-07-09 11:04 UTC
### Describe the Bug

When passed the following code:

```astro
---
const test = '123'
---

<Fragment set:html={`<style>${test}</style>`} />
```

It fails to parse in VSCode with the following errors:

![Failing to parse the linked code](https://user-images.githubusercontent.com/9100169/178102926-3bbb9c7f-aeb9-4153-aaee-01cd0eb8913f.png)

### Steps to Reproduce

1. `npm init astro` using template blog-starter
2. Use the code sample linked
3. See the error listed above

**Comment by Princesseuh** [comment] 2022-07-09 18:23
This happens because our current TSX generator thinks the style tag inside the string is a real style tag and as such, adds template literals inside it 

The new TSX output from the compiler should fix this issue. In the meantime, the following should work:

```html
<style set:html={rawStylesCSS}></style>
```

**Comment by Princesseuh** [comment] 2022-08-25 18:41
Closing as a duplicate of https://github.com/withastro/language-tools/issues/135

**Closed by Princesseuh** 2022-08-25 18:41 UTC
Labels: bug, needs-compiler
