### ISSUE TITLE
🐛 BUG: astro-vscode extension .astro file(component) import error.

### ISSUE THREAD

**Issue by CodeVxDev** [withastro/language-tools#781] opened 2024-02-10 09:16 UTC
### Describe the Bug

The Astro vscode extension version 2.7.0 and above gives an error stating "Cannot find module '@/components/\<component-name\>' or its corresponding type declarations." while importing components.

![image](https://github.com/withastro/language-tools/assets/149132260/955ac368-7948-4a4b-af2f-16ec572c7744)

tsconfig:

```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "strictNullChecks": true,
    "baseUrl": ".",
    "verbatimModuleSyntax": true,
    "paths": {
      "@/components/*": ["src/components/*.astro"],
      "@/layouts/*": ["src/layouts/*.astro"],
      "@/utils": ["src/utils/index.ts"],
      "@/data/*": ["src/data/*"],
      "@/site-config": ["src/data/site.config.ts"],
      "@/styles": ["src/styles/"],
    },
  },
  "exclude": ["node_modules", "**/node_modules/*", ".vscode", "dist"],
}
```
It was working fine until version 2.6.3.

### Steps to Reproduce

1. Upgrade Astro vscode extension to version 2.7.0 or above.
2. Add a tsconfig.json file with the below configurations.
```json{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "strictNullChecks": true,
    "baseUrl": ".",
    "verbatimModuleSyntax": true,
    "paths": {
      "@/components/*": ["src/components/*.astro"],
      "@/layouts/*": ["src/layouts/*.astro"],
      "@/utils": ["src/utils/index.ts"],
      "@/data/*": ["src/data/*"],
      "@/site-config": ["src/data/site.config.ts"],
      "@/styles": ["src/styles/"],
    },
  },
  "exclude": ["node_modules", "**/node_modules/*", ".vscode", "dist", ".husky", ".astro"],
}
```
3. Import any .astro component into the index.astro or any other component.
4. Error! "Cannot find module '@/components/\<component-name\>' or its corresponding type declarations."

**Comment by Princesseuh** [comment] 2024-02-10 09:20
Duplicate of https://github.com/withastro/language-tools/issues/778

**Closed** 2024-02-10 09:20 UTC
Labels: needs triage
