### ISSUE TITLE
💡 RFC: Prettier shouldn't be required to edit astro files

### ISSUE THREAD

**Issue by rightaway** [withastro/language-tools#531] opened 2023-05-09 20:48 UTC
### Background & Motivation

I don't want any prettier formatting. I just want the syntax highlighting for astro. The basic format on save that vscode provides in all file types like indenting is enough.

Using an opinionated formatter shouldn't be required at all to edit astro files.

### Possible solutions

A configuration option to disable prettier or to only provide syntax highlighting.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment] 2023-05-09 22:40
> The basic format on save that vscode provides in all file types like indenting is enough.

This does not exist, VS Code formatters are always provided by something and comes with their opinions. 

We could have a setting to disable formatting, but that would leave you with no formatting at all. Would that be satisfactory for your use case?

**Comment by rightaway** [comment] 2023-05-09 23:41
Disabling it can already be done with `"[astro]": { "editor.defaultFormatter": "none" }`.

vscode already has some basic indentation helpers which indent css, js and html files correctly when a file is saved. If we can have it use those formatters for the relevant parts of the .astro file then we can control the format of the file without prettier changing everything but still have a properly indented file.

So a setting to tell vscode to treat front matter like javascript and indent it as it normally would. And to treat the rest of the file as regular html and indent it too and also indent <style> and <script> tags as css and javascript.

**Comment by Princesseuh** [comment] 2023-05-10 05:32
> vscode already has some basic indentation helpers which indent css, js and html files correctly when a file is saved. If we can have it use those formatters for the relevant parts of the .astro file then we can control the format of the file without prettier changing everything but still have a properly indented file.

Those are not "some basic indention helpers", they're full blown formatters provided by other services, TypeScript for the JavaScript parts and https://github.com/beautify-web/js-beautify for HTML and CSS.

We used to use those before migrating to Prettier, but it wasn't satisfying to users because they do not ultimately understand Astro files, so it would often fail, expressions would always be formatted in a wonky way (when they got formatted) and even worse, sometimes formatting would break the files completely 

TypeScript formatters especially are very capricious, any difference with TSX and they fail completely to format, so expressions with multiple roots didn't work, HTML comments didn't work, shorthand props didn't work etc. It's possible to make it work, but it's a lot of work to maintain, and since we had so many requests for Prettier support, we decided to all-in our efforts there (much like Svelte did)

Just to be clear, I'm not opposed to have alternative formatters (how I would love to have dprint support 😔), but it's unfortunately not super easy

**Comment by rightaway** [comment] 2023-05-10 18:15
Something like prettier is needed because of the custom syntax that astro uses.

```
{visible && <p>Show me!</p>}

{visible ? <p>Show me!</p> : <p>Else show me!</p>}

{filteredPosts.map((post) => <li><a href={post.url}>{post.frontmatter.title}</a></li>)}
```

Would you consider additionally supporting Vue style conditionals and loops such as `<astro-if>` and `<astro-for>`? Because those would be simple html tags so any existing formatter like js-beautify could support it out of the box. Then we can disable the astro formatting but keep the plugin enabled which would give us syntax highlighting and completions. It's best of both worlds.

Then we can tell vscode to use its default formatter as javascript for the front matter and html for the rest of the file. The basic formatters are enough to help writing code. js-beautify is also very customizable as you can disable most of its options and choose how you want your code to look.

Prettier changes things too much. It puts things on a single line or on multiple lines when you don't want it to because the whitespace you used helped the readability of the code. Prettier say they are an opinionated tool and they are not willing to create a plugin ecosystem or more options to allow other ways of writing code, and not every developer wants their code mangled that way.

This option will make astro appeal to the many developers who prefer Vue syntax to React syntax. And would help people who aren't using an already supported editor adopt astro because it's a more standard html syntax.

**Comment by rightaway** [comment] 2023-05-17 20:39
> Astro templating with JSX has worse devx than Vue

https://www.blackspike.com/blog/why-we-chose-astro-over-nuxt/

**Comment by Princesseuh** [comment] 2023-05-17 21:58
Even if we were to add this syntax, you still would not be able to use other formatters due to the frontmatter syntax. Additionally, even if you fixed that, with an `astro-for`, etc, it's very unlikely that we would remove expressions, as they do so much more than what those flow tags do.

Having a formatter that would only work in certain files and potentially break other is impractical.

The only way out of Prettier is to write new formatters / adapt the other formatters. It's a lot of work and it's ultimately very low priority since Prettier is by far the most used formatter in web dev.

**Comment by rightaway** [comment] 2023-05-24 22:42
What do you think about adding that syntax so astro can appeal to people who like JSX style or Vue style?

People who use Vue style can still use expressions inside attributes and front matter. They can choose to use a regular html formatter because front matter is becoming more common so formatters could start supporting them out of the box.

**Comment by Princesseuh** [comment] 2023-05-25 06:19
It'd take months / a year+ of work, would be a nightmare to document (we generally don't do two ways of doing the same things) and is overall very unlikely to happen. It's more likely that we'll introduce flow components eventually, though that still would not fix not wanting Prettier.

I think you might be underestimating the work needed, even just on the formatting part 😅 Vue doesn't magically work in HTML formatters, every formatter has a specific Vue mode.

Feel free to submit a feature request in the discussions over at https://github.com/withastro/roadmap

**Comment by Princesseuh** [comment] 2023-09-14 11:28
Closing since this is not a bug. If you're interested in pushing a proposal forward, please create a discussion over on the roadmap repo: https://github.com/withastro/roadmap

We're always on the lookout for new very used platforms to support and we've love to eventually making a Astro plugin for formatters like dprint or Biome, but it's a lot of work when a vast majority seems satisfied by Prettier.

**Closed by Princesseuh** 2023-09-14 11:28 UTC
Labels: feature
