### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by fyndor** [withastro/language-tools#624] opened 2023-08-11 05:48 UTC
### Describe the Bug

False positive error occurs for me when I have an onclick event where the function call inside the event of one element does not have a semicolon at the end of the call, it will cause the second element's onclick event show an error saying it expects a semicolon.

The following shows an error for the "openNavBar()" call

`<a class="closebtn" onclick="closeNavBar()">&times;</a>
<button type="button" class="openbtn" onclick="openNavBar()">&#9776;</button>`

But if I add a semi colon to the first element's call, the following will fix the error:

`<a class="closebtn" onclick="closeNavBar();">&times;</a>
<button type="button" class="openbtn" onclick="openNavBar()">&#9776;</button>`

Notice the only change I made was to add a semicolon to the first element's onclick, which then removes the error from the second element's onclick.  This appears to be an erroneous error that does not cause any issues with the compiled code, but does appear to the developer there is an issue in their astro component.

### Steps to Reproduce

Put two elements in a component that both have onclick javascript event handlers of the form

`<tag onclick="function()">
<tag onclick="function2()">
`
The second element's onclick will show there is an error expecting a semicolon

**Comment by Princesseuh** [comment] 2023-08-11 05:49
Duplicate of https://github.com/withastro/language-tools/issues/587

**Closed by Princesseuh** 2023-08-11 05:49 UTC
