### ISSUE TITLE
🐛 BUG: Astro VSCode v0.29 no longer provides IntelliSense for import statements

### ISSUE THREAD

**Issue by ciaw** [withastro/language-tools#490] opened 2023-03-07 06:38 UTC
### Describe the Bug

I recently switched to the pre-release (0.29.6) version of the Astro VSCode extension to solve issues regarding AlpineJS tags flagging errors.

The new version solved that issue, but now no longer is providing suggestions regarding imports the way it used to.

### Steps to Reproduce

For example in extension v0.28.2 if I type "import Ima" I get the following:
![Screenshot 2023-03-07 at 4 52 21 pm](https://user-images.githubusercontent.com/47731589/223340076-360df303-618f-4750-996c-c8a9eaddfc6c.png)

But in v0.29.6 I get nothing:
![Screenshot 2023-03-07 at 4 51 00 pm](https://user-images.githubusercontent.com/47731589/223340225-47c103e1-4335-45e6-bfbd-afb6764d8275.png)

I have tried uninstalling/reinstalling, different v0.29 versions. Nothing changes the above behaviour. Any help would be greatly appreciated. Thank you.

VSCode Version: 1.76.0
Astro Extension Version: 0.29.6
Astro Version: 2.0.18

Project Dependencies:
"dependencies": {
		"@astrojs/alpinejs": "^0.1.3",
		"@astrojs/image": "^0.15.0",
		"@astrojs/sitemap": "^1.0.1",
		"@astrojs/tailwind": "^3.0.1",
		"@fontsource/eb-garamond": "^4.5.11",
		"@fontsource/montserrat": "^4.5.14",
		"@fontsource/raleway": "^4.5.12",
		"@types/alpinejs": "^3.7.1",
		"alpinejs": "^3.11.1",
		"astro": "^2.0.14",
		"sharp": "^0.31.3",
		"tailwindcss": "^3.2.7"
	}

**Comment by Princesseuh** [comment] 2023-03-08 12:16
Unfortunately, this is nothing on your end. It's probably a regression caused by the way the new TSX output in 0.29.0 handles semicolons, TypeScript is incredibly picky about this, similar issues even arise inside `.ts` files at times.

We'll take a look!

**Comment by tedawf** [comment] 2023-04-18 05:26
I have this same issue with the import statements and also intellisense is not working at all even for vanilla astro. I was using the pre-release vscode extension v0.29.7 and I switched back to the release version v0.28.2 and I got back the usual intellisense. 

v0.28.2 (release)
![image](https://user-images.githubusercontent.com/17540318/232678933-61fcfc90-126d-4293-a14f-3c7d97e9dabf.png)

v0.29.7 (pre-release)
![image](https://user-images.githubusercontent.com/17540318/232679068-8eeeb7f2-60dc-46ee-bdfc-11b85b8ce284.png)
No intellisense or code completion at all.

I am using vscode-insiders if that matters but I test it on vscode as well and it's the same issue.

**Comment by Princesseuh** [comment] 2023-05-01 10:10
> I have this same issue with the import statements and also intellisense is not working at all even for vanilla astro. I was using the pre-release vscode extension v0.29.7 and I switched back to the release version v0.28.2 and I got back the usual intellisense.
> 
> v0.28.2 (release) ![image](https://user-images.githubusercontent.com/17540318/232678933-61fcfc90-126d-4293-a14f-3c7d97e9dabf.png)
> 
> v0.29.7 (pre-release) ![image](https://user-images.githubusercontent.com/17540318/232679068-8eeeb7f2-60dc-46ee-bdfc-11b85b8ce284.png) No intellisense or code completion at all. Also, as you can see, it highlights the wrong line as an error.
> 
> I am using vscode-insiders if that matters but I test it on vscode as well and it's the same issue.

Any chance you could share the code of this file where it doesn't work?

**Comment by tedawf** [comment] 2023-05-01 16:37
I'm sorry, I'm currently unable to reproduce this as the vscode extension for Astro just reached v1.0.0 and I can't switch between release and pre-release version anymore. I'm not sure if the pre-release version still exists but anyways, seems like a non-issue now for me.

**Comment by Princesseuh** [comment] 2023-05-01 16:43
The 1.0.0 is the same as the pre-release, so if it works for you now on 1.0.0, then everything is fine 😄

**Comment by mdmoreau** [comment] 2023-05-01 22:21
Ran into the import autocomplete issue after updating to v1.0.0 today - rolling back to v0.28.2 looks like it fixed it though.

**Comment by Princesseuh** [comment] 2023-06-02 21:22
Should be fixed by https://github.com/withastro/language-tools/pull/534

Feel free to create a new issue if this still happens!

**Closed by Princesseuh** 2023-06-02 21:22 UTC
Labels: bug, tsx-output

**Comment by mdmoreau** [comment] 2023-06-02 21:32
@Princesseuh latest version working perfectly so far - appreciate all your work here!
