### ISSUE TITLE
🐛 BUG: Setting a `for` Attribute on a Div Causes the Component To Fail Type Check

### ISSUE THREAD

**Issue by zicklag** [withastro/language-tools#379] opened 2022-08-17 21:32 UTC
### Describe the Bug

I have a component that's entire contents is this:

```html
<label for="hi"></label>
```

If I import that component I get the following type check error:

    File [my_file] is not a module.

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Create a `.astro` component with the only the following line in it `<label for="test"></label>`
3. Import that component into another page/component

---

It is worth noting that while this fails the typecheck it still bundles and renders the site just fine.

**Comment by Princesseuh** [comment] 2022-08-18 01:20
Hello, thank you for creating this issue! This is a duplicate of https://github.com/withastro/language-tools/issues/352 which I still haven't made progress on. 

It's super weird that the word `for` in particular would cause this and no other keywords - no idea what's going on there 😔

**Closed** 2022-08-18 01:20 UTC

**Comment by zicklag** [comment] 2022-08-18 01:22
Thanks for the quick reply! Even more weird is the fact that as I built on my component further, the issue went away at some point, even though I'm still using the `for` attribute in it. :shrug: 

In cas it helps, here's my working widget that includes the `for` keyword. I haven't tried to reduce it down to what made it work again:

```astro
---
export interface Props {
  id: string;
  end?: boolean;
  mobile?: boolean;
}

const { id, end, mobile } = Astro.props as Props;

const drawerModifiers = [
  {
    "drawer-end": !!end,
    "drawer-mobile": !!mobile
  }
];
---

<div class:list={ ['drawer', drawerModifiers] }>
  <input id={id} type="checkbox" class="drawer-toggle" />
  <div class="drawer-content">
    <slot name="page-content" />
  </div>
  <div class="drawer-side overflow-x-hidden">
    <label for={id} class="drawer-overlay"></label>

    <ul class="menu overflow-y-auto w-80 bg-base-100">
      <!-- Sidebar content here -->
      <slot name="drawer-content" />
    </ul>
  </div>
</div>
```
