### ISSUE TITLE
🐛 BUG: TypeScript hints stop inside script tags as soon as the script tag has attributes

### ISSUE THREAD

**Issue by MarcusOtter** [withastro/language-tools#440] opened 2022-10-25 21:35 UTC
### Describe the Bug

Bit of a weird one but here is the gist of it (inside an Astro file, at the bottom of `<body>`):
| Has TS checking | No TS checking |
| ---------------- | ---------------- |
| ![image](https://user-images.githubusercontent.com/35617441/197885153-5039b989-f2e5-4d29-b666-45d32d5ff764.png) | ![image](https://user-images.githubusercontent.com/35617441/197885222-917eca1d-b90b-49e2-a6df-4860e94ca364.png) |

Seems like it works with any attribute on the script tag.

Now for ME this was useful because I actually don't want to use TypeScript here so ... I might've done this:
![image](https://user-images.githubusercontent.com/35617441/197885633-bec997e6-46ff-4ce5-a573-f38fcca6e5fd.png)

But figured it's probably not intended so might as well report it. Would be nice to be able to opt out from TypeScript in some other way.

Locally I am using v0.28.1 of the VSCode extension and v1.5.0 of Astro.

### Steps to Reproduce

1. Go to https://astro.new and select the "Just the basics" template. For example, the image above is from [gitpod](https://astro.new/basics?on=gitpod). Have also been able to replicate it locally on my machine.
2. Open `Layout.astro` and add a `<script>` tag at the bottom of `<body>` (line 20)
3. Call a method that doesn't exist and see TypeScript error
4. Add any attribute on the `<script>` tag and see TypeScript error go away
5. Expected: Error probably shouldn't go away

**Comment by Princesseuh** [comment] 2022-10-25 22:23
Putting an attribute on a script tag remove hoisting, so it also removes TypeScript support. 

This means that script tags become JavaScript, so you'd need `checkJs` to see errors

**Comment by MarcusOtter** [comment] 2022-10-25 22:53
I see! It felt unintentional, but I'm not sure how this could be expressed more clearly to the developer. It could maybe be with a hint when you add any attribute, saying that this script is not hoisted, but that feels a bit spammy & kind of abusing what hints are for. Feel free to close this unless you feel like it's worth investigating how this could be made more clear 😄

**Comment by Princesseuh** [comment] 2022-10-25 23:13
Will close as a duplicate of https://github.com/withastro/language-tools/issues/323 😄

**Closed** 2022-10-25 23:13 UTC
