### ISSUE TITLE
🐛 BUG: Missing trailing backslash in void elements breaks code highlighting when inside a map method

### ISSUE THREAD

**Issue by Axelgustavschnurer** [withastro/language-tools#852] opened 2024-04-12 23:01 UTC
### Describe the Bug

As title suggests, using a void element such as <br> without a trailing backslash and within a map method causes syntax highlighting to break. Example in the code below:

```astro
---
let data = [
  'string 1',
  'string 2',
  'string 3'
]
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width" />
    <meta name="generator" content={Astro.generator} />
    <title>Astro</title>
  </head>
    <body>
      <h1>Astro</h1>
        {data.map(element => (
	  <p>{element}</p><br>
        ))}
  </body>
</html>
```

### Steps to Reproduce

1. `npm create astro@latest`
2. Create an array
3. Use the map method to map the array
4. Use any void element without a trailing backslash in the map method, ex. <br>, <img> or <input>
5. The syntax highlighting for the map function aswell as some closing html tags beneath the void element breaks. 
6. The expected behavior should be that the void element behaves  as it does outside the mapping function, where the lack of a trailing backslash does not cause the syntax highlighting to break.

**Comment by Princesseuh** [comment] 2024-04-13 01:11
Duplicate of https://github.com/withastro/language-tools/issues/708

**Closed by Princesseuh** 2024-04-13 01:11 UTC
Labels: needs triage
