### ISSUE TITLE
🐛 BUG: Incorrect syntax highlighting of self-closing HTML tags

### ISSUE THREAD

**Issue by ThomasGysemans** [withastro/language-tools#978] opened 2024-11-28 12:36 UTC
### Describe the Bug

Hi, I'm sorry if this is not the place to submit issues on syntax highlighting. If it isn't, please let me know where I can redirect this issue.

Anyway, let me illustrate the issue with some silly HTML. Look at this code (in a `.astro` file):

```astro
---
const language = "FR";
---

<div class="">
    <nav class="">
        <div class="">
            {language === "FR" ? (
                <a href="" class="">
                    <span class="">blablabla</span>
                </a>
            ) : (
                <a href="/">
                    <img src="/logo.png" alt="Logo" class="">
                </a>
                <h1 class="">Thomas<br>G</h1>
            )}
        </div>
        <div class="">
            <a href="" class="">
                VITRINE DE MES PROJETS
            </a>
        </div>
    </nav>
    <div>
        <slot />
    </div>
</div>

<style>
    p {
        color: red;
    }
</style>
```

The syntax highlighting is off and it is because of the missing closing `/` on the `<img>` and `<br>` tags.

The problem arises even on GitHub's syntax highlighting.

### Steps to Reproduce

Just copy paste the code above in a `.astro` file.

### Link to Minimal Reproducible Example

https://gist.github.com/ThomasGysemans/1198b77482498ab8d147cef7e567bf79

**Comment by Princesseuh** [comment] 2024-11-28 14:04
Duplicate of https://github.com/withastro/language-tools/issues/708

**Closed by Princesseuh** 2024-11-28 14:04 UTC
Labels: needs triage
