### ISSUE TITLE
🐛 BUG: Variables returned from component script are marked as unused by `noUnusedLocals`

### ISSUE THREAD

**Issue by robertrbairdii** [withastro/language-tools#745] opened 2023-12-29 02:58 UTC
### Describe the Bug

I was attempting to refactor a shared helper for returning a 404 response when an entity could not be found using code similar to what is found in the [documentation](https://docs.astro.build/en/guides/server-side-rendering/#response).

Here is a simple example demonstrating an issue visible both in VS Code with the Astro plugin and when running `astro check` via the terminal.

```astro
---
const { slug } = Astro.params

const notFoundResponse = new Response(null, {
  status: 404,
  statusText: 'Not found',
});

if(slug !== 'about') {
  return notFoundResponse
}
---

<div>{slug}</div>
```

This code will mark `notFoundResponse` as unused and give a typescript error when `noUnusedLocals` is enabled.

If the variable definition is removed, the type of `notFoundResponse` is then inferred as `any` and typescript does not warn that the variable is undefined which can especially be problematic if it is supposed to be a function like the following example:

```astro
---
const { slug } = Astro.params

if(slug !== 'about') {
  return getNotFoundResponse()
}
---

<div>{slug}</div>
```

### Steps to Reproduce

1. `npm init astro` with strictest typescript config (`noUnusedLocals` should be enabled to make the problem more visible in VS Code)
2. Configure the application for SSR
3. Create a page component that contains a variable returned in the component script portion of an astro component
4. Observe that the variable is marked as unused within VS Code and when running `astro check`

**Comment by Princesseuh** [comment] 2023-12-29 03:32
Duplicate of https://github.com/withastro/language-tools/issues/476

**Closed by Princesseuh** 2023-12-29 03:32 UTC
Labels: needs triage
