### ISSUE TITLE
🐛 BUG: autocompletion seems not work properly for pandacss

### ISSUE THREAD

**Issue by Hunnnn77** [withastro/language-tools#716] opened 2023-12-05 16:01 UTC
### Describe the Bug

```jsx
# there are no problems in this area (both key, value field are working)
const css1 = css({
  fontSize: '2xl',
  fontWeight: 'bold',
});

const css2 = css({
  fontSize: 'xl',
  fontWeight: 'normal',
});
---
# problems here, autocompletion for keys of object are not working. 
# but luckly if typed key, value field is working
<div
    class={css({
      fontSize: '2xl',
      fontWeight: 'bold',
    })}
  >
</div>
```

### Steps to Reproduce

1. that seems not a bug, but unsupported.

**Comment by Princesseuh** [comment] 2023-12-06 02:12
Duplicate of https://github.com/withastro/language-tools/issues/648

**Closed by Princesseuh** 2023-12-06 02:12 UTC
Labels: needs triage
