### ISSUE TITLE
🐛 BUG: The TS Server crashes on version 2.1.x when moduleResolution is node16, nodenext or bundler

### ISSUE THREAD

**Issue by haodong404** [withastro/language-tools#622] opened 2023-08-03 10:41 UTC
### Describe the Bug

The TS Server crashes on version 2.1.x, I'm not sure if it's the same as #614.

### Steps to Reproduce

**This bug is easy to replicate.** 
1. `pnpm create astro@latest`
2. `pnpm astro add solid`
3. Add `moduleResolution: "Node16"` to `tsconfig.json`.
```
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "module": "Node16",
    "moduleResolution": "Node16",
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```
4. Create a `.ts` or `.tsx` file, and restart the VS Code, you'll notice that the TS Server crashed 5 times.

**I've tried different versions of the Astro plugin, the bug occurs only if version >= 2.1.1**

**Comment by Princesseuh** [comment] 2023-08-03 14:50
cc @johnsoncodehk

**Comment by johnsoncodehk** [comment] 2023-08-03 16:26
I'll check it next week.

**Comment by otaviomad** [comment] 2023-08-04 07:41
Author of #614 here. We're using bundler moduleResolution as well. That might just be the cause.

**Comment by otaviomad** [comment] 2023-08-04 08:21
> That's weird, I'm using `moduleResolution: bundler` in all my personal Astro projects and it works 🤔 Could be a TypeScript version or OS thing perhaps?

The issue only occurs for me after I start using content collections. Maybe you're not using them?

**Comment by ched-dev** [comment] 2023-08-18 18:08
I'm experiencing this error too. I am using an npm package that requires `"moduleResolution": "nodenext"` to support it's typescript defs.

**Comment by johnsoncodehk** [comment] 2023-08-19 14:46
This seems to be a problem that needs to be fixed in TS, here is a quick fix:

- Use workspace tsdk
- Open node_modules/typescript/lib/tsserver.js, search `function getScriptKind` and add following code.
```diff
function getScriptKind(fileName, host) {
+  if (fileName.endsWith('.astro')) return 4;
  return ensureScriptKind(fileName, host.getScriptKind && host.getScriptKind(fileName));
}
```

**Closed** 2023-08-23 14:18 UTC
