### ISSUE TITLE
🐛 BUG: Formatting Layout components gives unexpected reults

### ISSUE THREAD

**Issue by jmayergit** [withastro/language-tools#846] opened 2024-03-28 07:02 UTC
### Describe the Bug

Astro extension for VSCode configured with Prettier

Layout structure

```
<html>
  <head>
    <AstroComponent />
  </head>
  <body>
  </body>
</html>

<script src=""></script>
```

Above, the Layout component (an Astro component) has another Astro component (AstroComponent) in the head and a script located outside the `<html>`

I suppose this is invalid html to have script tags located outside the html element however given "Template Syntax" [documentation](https://docs.astro.build/en/basics/astro-syntax/) it's expected to be a valid Astro component

Formatting this document will move the script tag inside the html element

### If there is no Astro component located in the head then the script and/or style tags located outside the html tag are not moved inside the html tag when formatting, and thus the result is expected

Full Layout component provided in steps to reproduce

Where should we place script tags in Layout components? Will astro still process these?

### Steps to Reproduce

1. `pnpm create astro@latest`
2. select "Use blog template" when bootstrapping
4. cd [randomly-generated-project-name]
5. open `apps/astro-app/src/layouts/main.astro` and copy paste Layout component

<details><summary>Layout component</summary>

```Astro
---
import type { CollectionEntry } from "astro:content";
import BaseHead from "../components/BaseHead.astro";
import Header from "../components/Header.astro";
import Footer from "../components/Footer.astro";
import FormattedDate from "../components/FormattedDate.astro";

type Props = CollectionEntry<"blog">["data"];

const { title, description, pubDate, updatedDate, heroImage } = Astro.props;
---

<html lang="en">
  <head>
    <BaseHead title={title} description={description} />
    <style>
      main {
        width: calc(100% - 2em);
        max-width: 100%;
        margin: 0;
      }
      .hero-image {
        width: 100%;
      }
      .hero-image img {
        display: block;
        margin: 0 auto;
        border-radius: 12px;
        box-shadow: var(--box-shadow);
      }
      .prose {
        width: 720px;
        max-width: calc(100% - 2em);
        margin: auto;
        padding: 1em;
        color: rgb(var(--gray-dark));
      }
      .title {
        margin-bottom: 1em;
        padding: 1em 0;
        text-align: center;
        line-height: 1;
      }
      .title h1 {
        margin: 0 0 0.5em 0;
      }
      .date {
        margin-bottom: 0.5em;
        color: rgb(var(--gray));
      }
      .last-updated-on {
        font-style: italic;
      }
    </style>
  </head>

  <body>
    <Header />
    <main>
      <article>
        <div class="hero-image">
          {
            heroImage && (
              <img width={1020} height={510} src={heroImage} alt="" />
            )
          }
        </div>
        <div class="prose">
          <div class="title">
            <div class="date">
              <FormattedDate date={pubDate} />
              {
                updatedDate && (
                  <div class="last-updated-on">
                    Last updated on <FormattedDate date={updatedDate} />
                  </div>
                )
              }
            </div>
            <h1>{title}</h1>
            <hr />
          </div>
          <slot />
        </div>
      </article>
    </main>
    <Footer />
  </body>
</html>

<script src=""></script>
```

</details>

6. Format document
7. script tag is moved unexpectedly

```Bash
diff --git a/src/layouts/BlogPost.astro b/src/layouts/BlogPost.astro
index bcebf6b..b2a1c85 100644
--- a/src/layouts/BlogPost.astro
+++ b/src/layouts/BlogPost.astro
@@ -85,7 +85,5 @@ const { title, description, pubDate, updatedDate, heroImage } = Astro.props;
       </article>
     </main>
     <Footer />
-  </body>
+  </body><script src=""></script>
 </html>
-
-<script src=""></script>
```

**Comment by Princesseuh** [comment] 2024-03-28 08:03
Duplicate of https://github.com/withastro/prettier-plugin-astro/issues/316

**Closed by Princesseuh** 2024-03-28 08:03 UTC
Labels: needs triage
