### ISSUE TITLE
🐛 BUG: vscode, language service lost permanently / TS Service likewise / flacky import-suggest

### ISSUE THREAD

**Issue by akomm** [withastro/language-tools#707] opened 2023-11-21 13:52 UTC
### Describe the Bug

It appears the language server is constantly crashing or losing information, leading to different errors like this:
![grafik](https://github.com/withastro/language-tools/assets/2409779/04b67091-0f96-4b30-8ea9-4e57a98a9aae)

I have to restart the extension host to recover. Its happening very frequent. When working every 3-5 minutes, sometimes just few seconds after recover. I think it depends on actions, but I'm not sure which. Maybe creating new files or folders.

I have also TS installed as dependency, same version as the one used by astro:
![grafik](https://github.com/withastro/language-tools/assets/2409779/961f6800-0ac5-4507-aff4-6aca6f44e2d3)
But it also keeps constantly hanging, it never finishes loading until I restart extension host:
![grafik](https://github.com/withastro/language-tools/assets/2409779/148506c9-8b09-4519-8907-5e5b929cb810)

Even after the service is back and not hanging: Import-suggest is also very flacky: I have to hit escape to close the wrong suggests, then ctrl+space again for the proper import to appear:
[flacky.webm](https://github.com/withastro/language-tools/assets/2409779/cae2d336-5f6e-4c01-a9fd-cb4a8336d5b6)

I have around 30 different projects and use TS, I do not have the same issue there. It only appears when I work in an astro project with the astro plugin enabled. 

### Steps to Reproduce

1. `yarn create astro`
2. empty project
3. install dependencies
4. use TS (strictest)
5. add typescript explicitly
6. Well and here just creating .astro and .ts files the error RANDOMLY kicks in.

ubuntu 22.04.3 lts
node 18.18.2
yarn 4.0.2
astro 3.5.5
typescript 5..2.2

.vscode/settings.json
```json
{
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "typescript.tsdk": "node_modules/typescript/lib",
  "[astro]": {"editor.defaultFormatter": "astro-build.astro-vscode"},
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": "explicit"
  }
}
```

**Comment by akomm** [comment] 2023-11-21 14:10
I have now experienced an actual TS Server crash with some error output:
![grafik](https://github.com/withastro/language-tools/assets/2409779/a151f7bb-81b5-47fc-b1d2-9b707d615558)

**Comment by jhechtf** [comment] 2024-03-06 00:38
I'm not 100% that this is related but I've noticed that in VSCode on an Astro project I lose basically anything pertaining to types as long as the `Astro` extension is enabled

```sh
pnpm astro --version

   astro  v4.4.11
```

```sh
code --version
1.87.0
```

```json
"@astrojs/react": "^3.0.10",
"@astrojs/tailwind": "^5.1.0",
"@astrojs/vue": "^4.0.8",
```

TSConfig

```json

{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ],
      "@/*": [
        "./components/*"
      ]
    },
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  },
  "exclude": [
    "dist"
  ],
  
  "extends": "astro/tsconfigs/strict"
}
```

astro.config.mjs

```js
import { defineConfig } from 'astro/config';
import { resolve } from 'node:path';
import vue from '@astrojs/vue';
import tailwind from '@astrojs/tailwind';
import react from "@astrojs/react";

// https://astro.build/config
export default defineConfig({
  integrations: [vue(), tailwind(), react()],
  vite: {
    resolve: {
      alias: {
        '~': './',
        '@': resolve('./components'),
        'config': resolve('./configs/config.json')
      }
    }
  }
});
```
With the Astro extension enabled. Got here by hitting `ctrl+spacebar` and hitting the up arrow

![image](https://github.com/withastro/language-tools/assets/8152471/d8f74eac-4e89-4f29-a286-872a58f6c2fc)

With Astro extension disabled, navigated to in the same was noted above

![image](https://github.com/withastro/language-tools/assets/8152471/5f2a3e90-c1a5-4699-bdfb-74704f10e307)

**Comment by Princesseuh** [comment] 2024-05-07 13:31
This is a bit of a bucket issue, I suspect a fair amount of the more important issues here are not necessarily related to each other and/or have been fixed already. The "flaky imports" for instance is unrelated to the rest, and is caused by how right now show HTML completions in priority when they exists (see https://github.com/withastro/language-tools/discussions/769)

Since there's not a lot of activity here or similar reports on Discord, I don't think it's quite as pervasive as it might seems. I'll close this issue since there's nothing actionable here, I'm sorry for the inconvenience. If this still happens, please feel free to open a new issue with more details about your setup.

**Closed by Princesseuh** 2024-05-07 13:31 UTC
Labels: ecosystem: upstream, needs investigation

**Comment by Princesseuh** [comment] 2024-05-07 15:53
> So you're closing my issues, because others have posted an issue they thought is related? How does this make any sense?

No? I didn't mention any other messages or user reports, just what you posted. Your first message has multiple unrelated issues in the same message.

- The first screenshot I believe is fixed
- The second screenshot about the "Loading Intellisense Status" is unrelated to the first issue, you're showing the state of tsserver, not the Astro LSP. I also believe this to be fixed.
- The "flaky imports" as mentioned is unrelated and already has a discussion specific for it

In your second message, the tsserver crash is also unrelated to the issues inside Astro files, and I believe it to be fixed as well.

Apologies if my message was unclear.

**Comment by akomm** [comment] 2024-05-08 08:33
Thanks.

It is never clear when posting a bug whether observed phenomenons are related or not. Leaving out details can't be the solution. When you expect people to reproduce, record and picture issues and then recreate it over and over again because it turns out to be separate, its going to create friction that people just don't report and go along with the systems that they already use and which works.

**Comment by Princesseuh** [comment] 2024-05-08 08:59
> Thanks.
> 
> It is never clear when posting a bug whether observed phenomenons are related or not. Leaving out details can't be the solution. When you expect people to reproduce, record and picture issues and then recreate it over and over again because it turns out to be separate, its going to create friction that people just don't report and go along with the systems that they already use and which works.

I never said you should've done anything differently. I'm closing the issue because I believe (I can't reproduce it and there's no other reports, so hard to say 100%, but I believe so) the issues to be fixed, and there's already more precise bug reports / feature requests for the ones that aren't fixed.

Had I disagreed with the format of the issue, I would've sent a comment asking for clarifications / closed the issue when I first triaged it in December. There's no animosity here, you did everything correctly.
