### ISSUE TITLE
🐛 BUG: Astro's <ViewTransitions /> routing component formatting breaks

### ISSUE THREAD

**Issue by golamrabbiazad** [withastro/language-tools#651] opened 2023-09-16 11:31 UTC
### Describe the Bug

Formatting breaks on save when the `<ViewTransitions />` routing component is added in the head section.

Example.

![Screenshot from 2023-09-16 16-18-08](https://github.com/withastro/language-tools/assets/35021384/1cf50f41-34c2-4721-b214-cc6daa69bcc5)

### Steps to Reproduce

1. npm create astro@latest
2. create a layout file in the layout folder
3. HTML markup added
4. style tag added
5. on save Formatting breaks

**Comment by Princesseuh** [comment] 2023-09-16 14:03
Duplicate of https://github.com/withastro/prettier-plugin-astro/issues/316

**Closed by Princesseuh** 2023-09-16 14:03 UTC
