### ISSUE TITLE
🐛 BUG: Tags inside `` backticks are treated as elements

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#135] opened 2021-12-14 19:13 UTC
### Describe the Bug

![image](https://user-images.githubusercontent.com/63650415/146063931-afc5da0b-b730-4b4e-b306-4e1e17d5a0eb.png)

### Steps to Reproduce

Tags inside strings should be treated as strings.

**Comment by Princesseuh** [comment] 2022-03-16 13:22
I'm not able to reproduce this. I'm thinking it might have been fixed by https://github.com/withastro/language-tools/pull/162

Can you confirm if this has been fixed on your end too?

**Comment by RafidMuhymin** [comment] 2022-03-16 18:15
![Peek 2022-03-17 00-14](https://user-images.githubusercontent.com/63650415/158659332-a97e0332-2548-4e7d-b53b-675edd63ca9e.gif)

**Closed** 2022-11-14 19:34 UTC
Labels: bug, needs-compiler
