### ISSUE TITLE
💡 RFC: Schema Check Collections via CLI

### ISSUE THREAD

**Issue by Mitsunee** [withastro/language-tools#697] opened 2023-11-14 18:10 UTC
### Background & Motivation

I have a project for a friend that includes a blog, therefore we're adding related Data and Content Collections for this feature and I added schemas for proper TypeScript support. I would like to be able to make a CI step that validates all collections against their schemas, but was not able to do this in any way. In the end I just skipped forward to creating the pages and having Astro actually consume the collections, which were then checked in dev/build.

The CI step would be useful for preventing full builds from starting while schemas checks would fail and possibly providing faster feedback to whoever writes for the blog. Furthermore such a feature could also check unused collections, as was the case for me before I created the actual routes that consume the collections. Currently with how schema checking is implemented in dev/build in Astro checks are only performed once a collection file (or the entire collection) is actually consumed.

### Possible solutions

Add the proposed functionality to `@astrojs/check` or a new package (`@astrojs/validate-collections` or something similar).

### Alternatives considered

Doing a full build instead, or just not doing schema checks before triggering a deployment build.

### Risks, downsides, and/or tradeoffs

A full build takes significantly longer and only checks collections that are actually in use.

### Open Questions

Whether to include the functionality in `@astrojs/check` or make it a new thing entirely.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment] 2023-11-14 21:07
Duplicate of https://github.com/withastro/roadmap/discussions/759

**Closed by Princesseuh** 2023-11-14 21:07 UTC
Labels: needs triage
