### ISSUE TITLE
Is crashing my ts server

### ISSUE THREAD

**Issue by J-Fannilla** [withastro/language-tools#860] opened 2024-04-24 08:29 UTC
Type: <b>Bug</b>

This extencion is crashing my ts server

Extension version: 2.8.6
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|17, 15, 14|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv|. --crash-reporter-id 0490d8e5-dce1-4079-86eb-ad8a61d984fb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
gee8j676:31009558
showvideot:31016892
chatpanelt:31018789
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31022790

```

</details>

**Comment by Princesseuh** [comment] 2024-04-24 10:26
I can't do anything with so little details. Also, a duplicate of https://github.com/withastro/language-tools/issues/850

**Closed by Princesseuh** 2024-04-24 10:26 UTC
Labels: needs triage
