### ISSUE TITLE
🐛 BUG: Moving global `style` tag into different tags automatically

### ISSUE THREAD

**Issue by MrDiamondDog** [withastro/language-tools#675] opened 2023-10-30 00:30 UTC
### Describe the Bug

When I have a `style` tag in my code, the auto-formatter decides to move it to a completely different place in the code, inside other tags. It only happens when using the `<ViewTransitions />` I have in the `head`

https://github.com/withastro/language-tools/assets/84212701/e8758099-7ae7-4ce3-b912-78e41a3484c2

### Steps to Reproduce

1. `npm init astro` using standard layout, strictest TS
2. Go into `Layout.astro`
3. Add `<ViewTransitions />` in `head`
4. Try saving

**Comment by Princesseuh** [comment] 2023-10-30 08:44
Duplicate of https://github.com/withastro/prettier-plugin-astro/issues/316

**Closed by Princesseuh** 2023-10-30 08:44 UTC
