### ISSUE TITLE
🐛 BUG: IntelliSense completions (w/ auto-imports) stops working until window is reloaded

### ISSUE THREAD

**Issue by baranelitez** [withastro/language-tools#983] opened 2024-12-12 19:50 UTC
### Describe the Bug

When a new .astro file is created under ./src/components, it requires VSCode to be restarted for autocomplete to work.

There had been cases where the first created file worked (after 5-6 saves on the file), but the second or third NEVER works.

Tried it in my computer, and also in a friend's computer with no prior vscode/pnpm/node installation to check if the case is on my side. The issue persists on friend's computer too.

### Steps to Reproduce

1. `pnpm create astro@latest` and choose basic and minimal template
2. open `.src/pages/index.astro`
3. remove the `<Welcome/>` component, and start typing `<Wel...`. Notice how it autocompletes.
4. create a new file called TestA.astro in `./src/components/`. Leave it empty.
5. go back to `.src/pages/index.astro`. Try typing `<Tes...`. Notice how it doesn't autocomplete
6. open command pallete and `Reload Window`. Try step `#5` again. Notice how it works now.
7. If  `#5` works without problems, try creating a file called `TestB.astro`. I could never make it work for the 2nd file.

### Link to Minimal Reproducible Example

non applicable. use the template. reproduction depends on manual file creation.

**Comment by baranelitez** [comment] 2024-12-12 19:55
Here, it works for the already existing Welcome.astro when I start typing
![image](https://github.com/user-attachments/assets/56fc6d93-1314-4227-b695-345f1b6894cc)
---
I create a file called `TestA.astro`. Now it doesn't autocomplete.
![image](https://github.com/user-attachments/assets/fba1538a-c33a-4335-8e72-752383a104e4)
![image](https://github.com/user-attachments/assets/1a08bf8f-5fad-479f-b946-b4670e5f1bff)
---
I reload VSCode, and it starts working
![image](https://github.com/user-attachments/assets/5c122db6-846f-4203-b95a-a793df4b300b)

**Comment by Princesseuh** [comment] 2024-12-12 22:29
Duplicate of https://github.com/withastro/language-tools/issues/958

**Closed by Princesseuh** 2024-12-12 22:29 UTC
Labels: needs triage
