### ISSUE TITLE
🐛 BUG: Installing date-fns package breaks import intellisense

### ISSUE THREAD

**Issue by thanh-nguyen-95** [withastro/language-tools#967] opened 2024-10-09 04:44 UTC
### Describe the Bug

Installing `date-fns` package makes Astro Language Server stops autocompletion on imports.

Everything works as intended if I'm using VSCode with the latest Astro extension (2.15.2).

Additional info:

- **OS**: Linux
- **Kernel version**: 6.6.52-1-lts
- **IDE**: Neovim 0.10.2 with Mason plugin for LSP
- **Node**: 20.17.0
- **Npm**: 10.8.2
- **Astro Language Server**: 2.15.0

### Steps to Reproduce

1. `npm init astro` using default options
2. `npm install date-fns`
3. Intellisense stops working

### Link to Minimal Reproducible Example

https://github.com/thanh-nguyen-95/astro-ls-error-with-date-fns

**Comment by Princesseuh** [comment] 2024-10-09 12:36
Seems to work fine for me: 

https://github.com/user-attachments/assets/28200abb-ef85-415a-9746-6bd6ed5c3af8

**Comment by thanh-nguyen-95** [comment] 2024-10-09 13:05
It DOES work in VSCode with the official extension as I mentioned in the bug report.

I'm using Neovim with a plugin, which uses `@astrojs/language-server` under the hood. I'm not sure why it stops working after I installed `date-fns` so I created an issue to see if anyone else has this problem. I assume the VSCode extension also uses `@astrojs/language-server` so it should work for be, but it's not.

I'm well aware this could be an edge case and could be solved by removing `date-fns`. Please feel free to close this issue if there's no further update.

**Comment by Princesseuh** [comment] 2024-10-09 13:25
Ah apologies, I missed that part of the original post. Unfortunately, I barely have the time to debug VS Code issues, and so Neovim issues are insanely low priority. I'm sorry.

They do both use the same language server, there's only one LS for Astro

**Comment by Fakerko** [comment] 2024-10-16 04:42
Guys, I have the same issue. When I add package date-fns, it completely broke .astro files intellisense. When I remove date-fns package, it's working again.

I tried uninstall all other VSCode plugins and tried fresh astro project, but it's caused by the date-fns.

**Comment by Fakerko** [comment] 2024-10-16 04:55
Recorded video to demonstrate the issue. When the date-fns is imported, only .astro files are broken.


https://github.com/user-attachments/assets/1745c393-fd2c-41d6-8676-55c0f30e9afd

**Comment by Fakerko** [comment] 2024-10-18 04:23
@Princesseuh this should be re-open, I am using VSCode not Neovim.

**Comment by Chipsnet** [comment] 2024-10-22 11:14
I have the same issue.

I noticed that my VSCode astro intellisense was broken and found this Issue, so I uninstalled date-fns and it works fine.

I am using the latest version of Astro extension and VSCode.

OS: Windows 11 23H2 (22631.4112)
IDE: Visual Studio Code 1.94.2
bun: 1.1.32
Astro Extension: 2.15.3
Astro version: 4.15.12

**Comment by Fakerko** [comment] 2024-10-29 06:20
After the Astro VSCode plugin last update to v2.15.4 its working as expected for now.

**Comment by Princesseuh** [comment] 2024-10-29 07:57
Awesome. Could anyone else confirm?

**Comment by Princesseuh** [comment] 2024-11-04 21:53
Closing, since it seems like this is fixed. Let me know if it still happens.

**Closed by Princesseuh** 2024-11-04 21:53 UTC
Labels: needs triage, needs investigation
