### ISSUE TITLE
🐛 BUG: `astro check` reports false positive unused variable when variable is used in `Astro.redirect`

### ISSUE THREAD

**Issue by fengelniederhammer** [withastro/language-tools#980] opened 2024-12-11 10:29 UTC
### Describe the Bug

`astro check` reports false positive when using import in `return Astro.redirect( --> here <-- )`.

For example here, it will report that `MyObject` is unused:
```
---
import { MyObject } from '../object';

return Astro.redirect(
    MyObject.asdfasdf,
);
---

``` 

This works as expected though (`astro check` recognizes `MyObject` as being used):
```
---
import { MyObject } from '../object';

let value = MyObject.asdfasdf;
return Astro.redirect(value);
---
``` 

A real-world example can be found in https://github.com/GenSpectrum/dashboards/blob/09e505a0bd82a87cf2d460dd3d70fff063eb1b0d/website/src/pages/covid/index.astro

### Steps to Reproduce

1. `npm create astro@latest`, `npx astro check` to install `@astrojs/check` - yields ATM:
```
  "dependencies": {
    "@astrojs/check": "^0.9.4",
    "astro": "^5.0.4",
    "typescript": "^5.7.2"
  }
``` 
2. `src/pages/index.astro`:
```
---
import { MyObject } from '../object';

return Astro.redirect(
    MyObject.asdfasdf, // access a key that does not exist
);
---
``` 
3. `src/object.ts`:
```typescript
export const MyObject = {
    helloWorld: 'Hello World!',
}
``` 
4. `npx astro check`:
```
$ npx astro check
11:12:10 [content] Syncing content
11:12:10 [content] Synced content
11:12:10 [types] Generated 26ms
11:12:10 [check] Getting diagnostics for Astro files in .../dashboards/astro/square-series...
src/pages/index.astro:2:1 - warning ts(6133): 'MyObject' is declared but its value is never read.

2 import { MyObject } from '../object';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Result (4 files): 
- 0 errors
- 0 warnings
- 1 hint
``` 
5. It reports a false positive on an unused variable (it is used - obviously). But it doesn't report the access to the non-existent key.

### Link to Minimal Reproducible Example

https://github.com/GenSpectrum/dashboards/commit/c209e4476fed55560a514c41a432487dd9f753a1

**Comment by Princesseuh** [comment] 2024-12-11 16:38
Duplicate of https://github.com/withastro/language-tools/issues/476

**Closed by Princesseuh** 2024-12-11 16:38 UTC
Labels: needs triage
