### ISSUE TITLE
`@astrojs/check` includes `/dist` and`/public`

### ISSUE THREAD

**Issue by cauboy** [withastro/language-tools#721] opened 2023-11-21 15:02 UTC
### Astro Info

```block
Astro                    v3.5.5
Node                     v20.7.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/preact
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Shell

### Describe the Bug

When I run `npx astro check` on my project it fails with the following error:

<details><summary>👈 Here's the output when running `npx astro check`</summary>

```
npx astro check

03:18:27 PM [@astrojs/cloudflare] The current configuration does not support image optimization. To allow your project to build with the original, unoptimized images, the image service has been automatically switched to the 'noop' option. See https://docs.astro.build/en/reference/configuration-reference/#imageservice
03:18:27 PM [content] No content directory found. Skipping type generation.
03:18:27 PM [check] Getting diagnostics for Astro files in /Users/john-doe/Code/my-project...

<--- Last few GCs --->

[47065:0x138008000]    41224 ms: Scavenge 4040.8 (4123.3) -> 4037.8 (4123.6) MB, 18.92 / 0.00 ms  (average mu = 0.560, current mu = 0.459) allocation failure;
[47065:0x138008000]    41239 ms: Scavenge 4042.2 (4123.6) -> 4040.6 (4127.6) MB, 9.04 / 0.00 ms  (average mu = 0.560, current mu = 0.459) allocation failure;
[47065:0x138008000]    42923 ms: Scavenge 4045.5 (4127.6) -> 4043.7 (4145.8) MB, 1677.71 / 0.00 ms  (average mu = 0.560, current mu = 0.459) allocation failure;


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x102d0e0e4 node::Abort() [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
 2: 0x102d0e2cc node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
 3: 0x102e92018 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
 4: 0x1030666e8 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
 5: 0x1030651c4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
 6: 0x10305b9dc v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
 7: 0x10305c23c v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
 8: 0x103041240 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
 9: 0x103428c50 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
10: 0x103788c44 Builtins_CEntry_Return1_ArgvOnStack_NoBuiltinExit [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
11: 0x1037028a8 Builtins_GrowFastSmiOrObjectElements [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
12: 0x1098ac084
13: 0x1098a9858
14: 0x1098a82cc
15: 0x108a94064
16: 0x1098ab1c4
17: 0x1093235ac
18: 0x109472ed4
19: 0x1098ae4dc
20: 0x1098aa8e0
21: 0x1094ea9b0
22: 0x10992fca4
23: 0x1090106e0
24: 0x108b3b9e0
25: 0x10992d2e0
26: 0x1037abee4 Builtins_ArrayMap [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
27: 0x1037003e4 Builtins_InterpreterEntryTrampoline [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
28: 0x1037003e4 Builtins_InterpreterEntryTrampoline [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
29: 0x1037003e4 Builtins_InterpreterEntryTrampoline [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
30: 0x103737210 Builtins_AsyncFunctionAwaitResolveClosure [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
31: 0x1037e4fb8 Builtins_PromiseFulfillReactionJob [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
32: 0x103726b94 Builtins_RunMicrotasks [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
33: 0x1036fe3f4 Builtins_JSRunMicrotasksEntry [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
34: 0x102fd3c58 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
35: 0x102fd4144 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
36: 0x102fd4320 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
37: 0x102ffb3dc v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
38: 0x102ffbb78 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
39: 0x102c40c64 node::InternalCallbackScope::Close() [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
40: 0x102c407c4 node::InternalCallbackScope::~InternalCallbackScope() [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
41: 0x102cb6b64 node::Environment::RunTimers(uv_timer_s*) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
42: 0x1036da73c uv__run_timers [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
43: 0x1036ddf9c uv_run [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
44: 0x102c41754 node::SpinEventLoopInternal(node::Environment*) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
45: 0x102d4e7e8 node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
46: 0x102d4e584 node::NodeMainInstance::Run() [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
47: 0x102cd9658 node::Start(int, char**) [/Users/john-doe/.nvm/versions/node/v20.7.0/bin/node]
48: 0x1890b10e0 start [/usr/lib/dyld]
[1]    47040 abort      npx astro check
```
</details>

Digging into the issue and adding some additional logging to  the `astro check` command, I could identify that the error happens while  the `/dist/_workers.js` is checked. After deleting the `dist` folder the `astro check` command succeeds.

This makes me wonder why astro is considering the `dist` folder at all. I also wasn't able to only check files in the `/src` folder by running `astro check --root ./src`.

A hack would be to update https://github.com/classictrader/cti-frontend/blob/chore/CTI-85-upgrade-to-astro-3-5-5/node_modules/@astrojs/check/node_modules/@astrojs/language-server/dist/check.js#L58 to 
```ts
        const files = fileNames !== undefined ? fileNames : this.project.languageHost.getScriptFileNames().filter(fileName => !fileName.includes('/dist/'));
```
But I'm sure there's a nicer solution :-) 

PS: The bug appeared after upgrading from Astro `2.10` to `3.5`. With Astro `2.10` the error never happened.

### What's the expected result?

- I expect to be able to run `npx astro check` without a  `JavaScript heap out of memory` error.
- I would expect that `npx astro check` doesn't consider the `dist` folder

### Link to Minimal Reproducible Example

-- I wasn't able to create a simple reproducible example (maybe b/c it depends on project size) --

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-12-11 17:33
Duplicate of https://github.com/withastro/language-tools/issues/643

I'll mention that the proper workaround at the moment is to set the folders you want to ignore in your `tsconfig.json`'s `exclude`. Much like you would for `tsc`.

**Closed by Princesseuh** 2023-12-11 17:33 UTC
Labels: - P3: minor bug, feat: check
