### ISSUE TITLE
🐛 BUG: Comment shortcut generates `//` within a JSX expression

### ISSUE THREAD

**Issue by bholmesdev** [withastro/language-tools#857] opened 2024-04-22 18:20 UTC
### Describe the Bug

When using the comment shortcut in VS Code (`cmd + /`), the editor generates a `//` within a JSX expression. We should generate a `{/* */}` block.

https://github.com/withastro/language-tools/assets/51384119/a7c1718b-23c6-4449-bb4b-f5b43da3b0d6

### Steps to Reproduce

1. Create a JSX expression in a `.astro` file
2. Use the comment shortcut `cmd + /`

**Comment by Princesseuh** [comment] 2024-04-22 18:25
Duplicate of https://github.com/withastro/language-tools/issues/713#issuecomment-2070469575

**Closed by Princesseuh** 2024-04-22 18:25 UTC
Labels: needs triage
